version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sunskog-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
volumes:
  mssql-data:
