@'
version: "3.9"

services:
  api:
    build:
      context: ./SunSkog.Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sqldata;Database=SunSkogDb;User Id=sa;Password=Your_strong_Password123;TrustServerCertificate=true
    ports:
      - "5250:8080"
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_Password123
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata:
'@ | Set-Content -Encoding UTF8 -NoNewline .\docker-compose.yml