# .github/workflows/dotnet-ci.yml
name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true            # rychlejší běhy (cache nuget balíčků)

      - name: Restore
        run: |
          dotnet restore SunSkog.Api/SunSkog.Api.csproj
          dotnet restore SunSkog.Api.Tests/SunSkog.Api.Tests.csproj

      - name: Build
        run: dotnet build SunSkog.Api/SunSkog.Api.csproj -c Release --no-restore

      - name: Test (collect coverage)
        run: >
          dotnet test SunSkog.Api.Tests/SunSkog.Api.Tests.csproj
          -c Release --no-build
          --collect:"XPlat Code Coverage"
          --logger "trx;LogFileName=test-results.trx"

      # ===== Artefakty s TRX a Cobertura XML =====
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: SunSkog.Api.Tests/TestResults
          retention-days: 14

      - name: Upload coverage (Cobertura)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: SunSkog.Api.Tests/TestResults/**/coverage.cobertura.xml
          retention-days: 14

      # ===== (Volitelné) HTML report pokrytí =====
      - name: Install ReportGenerator
        if: always()
        run: dotnet tool update -g dotnet-reportgenerator-globaltool

      - name: Add dotnet tools to PATH
        if: always()
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Generate HTML coverage report
        if: always()
        run: |
          reportgenerator \
            -reports:"SunSkog.Api.Tests/TestResults/**/coverage.cobertura.xml" \
            -targetdir:"coverage-report" \
            -reporttypes:Html

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage-report
          retention-days: 14

      # ===== (Volitelné) Shrnutí pokrytí do job Summary =====
      - name: Create Coverage Summary
        if: always()
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: SunSkog.Api.Tests/TestResults/**/coverage.cobertura.xml
          badge: true
          fail_below_min: false
          format: 'markdown'
          hide_branch: false
          indicators: true
          output: 'both'                # uloží i code-coverage-results.md
          thresholds: '60 80'           # červená/oranžová/zelená

      - name: Append Coverage Summary to Job Summary
        if: always()
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
